name = "create-server-modpack"
author = "eiiko6"
version = "1.9.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dda8216a6b142ec7b2e43431e197ee8e17859530ed68b8345adf9009157c8447"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
