name = "Create Server Modpack"
author = "eiiko6"
version = "1.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f657c34dd14f531d922398afd4d33c86242a1cc11e5517899139d744243c1379"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
