name = "Create Server Modpack"
author = "eiiko6"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "962cec09ae0dbd25d5fd9056505f3c3727a153a8ae0257619743fcb883641f3d"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
